import { member } from './src/invites'

member('EarthWittawat')
member('Feen0305')
member('FiFaKuBz')
member('Jwiitysan')
member('Mirailisc')
member('NEXT29297')
member('NinePTH')
member('pannawittt')
member('parunchxi')
member('Phattharyu')
member('RangsimanJera')
member('PlugsPakuko')
member('ShinakritLao')
member('smolguyonearth')
member('Srisuphadith')
member('Stxmplhz')
member('tikpoptv')
member('zflukz')
member('mmawin99')
